import jsPDF from 'jspdf';

export const exportToPDF = (plan, userData) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const lineHeight = 7;
  let yPosition = margin;

  const addText = (text, fontSize = 12, isBold = false) => {
    pdf.setFontSize(fontSize);
    if (isBold) {
      pdf.setFont(undefined, 'bold');
    } else {
      pdf.setFont(undefined, 'normal');
    }
    
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    
    lines.forEach(line => {
      if (yPosition > pdf.internal.pageSize.getHeight() - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(line, margin, yPosition);
      yPosition += lineHeight;
    });
    
    yPosition += 3;
  };

  addText('AI FITNESS COACH - PERSONALIZED PLAN', 20, true);
  yPosition += 5;

  addText('PERSONAL INFORMATION', 16, true);
  addText(`Name: ${userData.name}`);
  addText(`Age: ${userData.age} years`);
  addText(`Gender: ${userData.gender}`);
  addText(`Height: ${userData.height} cm`);
  addText(`Weight: ${userData.weight} kg`);
  addText(`Fitness Goal: ${userData.fitnessGoal.replace('-', ' ').toUpperCase()}`);
  addText(`Fitness Level: ${userData.fitnessLevel.toUpperCase()}`);
  addText(`Workout Location: ${userData.workoutLocation.toUpperCase()}`);
  addText(`Dietary Preference: ${userData.dietaryPreference.toUpperCase()}`);
  
  if (userData.medicalHistory) {
    addText(`Medical History: ${userData.medicalHistory}`);
  }
  
  if (userData.stressLevel) {
    addText(`Stress Level: ${userData.stressLevel.toUpperCase()}`);
  }
  
  yPosition += 10;

  addText('WORKOUT PLAN', 16, true);
  addText(plan.workout.replace(/\*\*/g, '').replace(/\*/g, ''));
  yPosition += 10;

  addText('DIET PLAN', 16, true);
  addText(plan.diet.replace(/\*\*/g, '').replace(/\*/g, ''));
  yPosition += 10;

  addText('AI TIPS & MOTIVATION', 16, true);
  addText(plan.tips.replace(/\*\*/g, '').replace(/\*/g, ''));

  const pageCount = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(10);
    pdf.setFont(undefined, 'normal');
    pdf.text(
      `Generated by AI Fitness Coach - Page ${i} of ${pageCount}`,
      margin,
      pdf.internal.pageSize.getHeight() - 10
    );
    pdf.text(
      `Generated on: ${new Date().toLocaleDateString()}`,
      pageWidth - margin - 50,
      pdf.internal.pageSize.getHeight() - 10
    );
  }

  const fileName = `${userData.name.replace(/\s+/g, '_')}_Fitness_Plan_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(fileName);
};